# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0002_auto_20160826_1849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'verbose_name': '版块', 'verbose_name_plural': '版块'},
        ),
    ]
