# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0003_auto_20160827_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='status',
            field=models.IntegerField(choices=[(0, '正常'), (-1, '删除')], default=0, verbose_name='状态'),
            preserve_default=False,
        ),
    ]
